export const ALL_CURRENCIES = {
  aed: 'United Arab Emirates Dirham',
  afn: 'Afghan Afghani',
  all: 'Albanian Lek',
  amd: 'Armenian Dram',
  ang: 'Netherlands Antillean Guilder',
  aoa: 'Angolan Kwanza',
  ars: 'Argentine Peso',
  aud: 'Australian Dollar',
  awg: 'Aruban Florin',
  azn: 'Azerbaijani Manat',
  bam: 'Bosnia-Herzegovina Convertible Mark',
  bbd: 'Barbadian Dollar',
  bdt: 'Bangladeshi Taka',
  bgn: 'Bulgarian Lev',
  bhd: 'Bahraini Dinar',
  bif: 'Burundian Franc',
  bmd: 'Bermudan Dollar',
  bnd: 'Brunei Dollar',
  bob: 'Bolivian Boliviano',
  brl: 'Brazilian Real',
  bsd: 'Bahamian Dollar',
  btn: 'Bhutanese Ngultrum',
  bwp: 'Botswanan Pula',
  bzd: 'Belize Dollar',
  cad: 'Canadian Dollar',
  cdf: 'Congolese Franc',
  chf: 'Swiss Franc',
  clp: 'Chilean Peso',
  cnh: 'Chinese Yuan Offshore',
  cny: 'Chinese Yuan',
  cop: 'Colombian Peso',
  cup: 'Cuban Peso',
  cve: 'Cape Verdean Escudo',
  czk: 'Czech Republic Koruna',
  djf: 'Djiboutian Franc',
  dkk: 'Danish Krone',
  dop: 'Dominican Peso',
  dzd: 'Algerian Dinar',
  egp: 'Egyptian Pound',
  ern: 'Eritrean Nakfa',
  etb: 'Ethiopian Birr',
  eur: 'Euro',
  fjd: 'Fijian Dollar',
  fkp: 'Falkland Islands Pound',
  gbp: 'British Pound Sterling',
  gel: 'Georgian Lari',
  ghs: 'Ghanaian Cedi',
  gip: 'Gibraltar Pound',
  gmd: 'Gambian Dalasi',
  gnf: 'Guinean Franc',
  gtq: 'Guatemalan Quetzal',
  gyd: 'Guyanaese Dollar',
  hkd: 'Hong Kong Dollar',
  hnl: 'Honduran Lempira',
  hrk: 'Croatian Kuna',
  htg: 'Haitian Gourde',
  huf: 'Hungarian Forint',
  idr: 'Indonesian Rupiah',
  ils: 'Israeli New Sheqel',
  inr: 'Indian Rupee',
  iqd: 'Iraqi Dinar',
  irr: 'Iranian Rial',
  isk: 'Icelandic Krona',
  jep: 'Jersey Pound',
  jmd: 'Jamaican Dollar',
  jod: 'Jordanian Dinar',
  jpy: 'Japanese Yen',
  kes: 'Kenyan Shilling',
  kgs: 'Kyrgystani Som',
  khr: 'Cambodian Riel',
  kmf: 'Comorian Franc',
  kpw: 'North Korean Won',
  krw: 'South Korean Won',
  kwd: 'Kuwaiti Dinar',
  kyd: 'Cayman Islands Dollar',
  kzt: 'Kazakhstani Tenge',
  lak: 'Laotian Kip',
  lbp: 'Lebanese Pound',
  lkr: 'Sri Lankan Rupee',
  lrd: 'Liberian Dollar',
  lsl: 'Lesotho Loti',
  lyd: 'Libyan Dinar',
  mad: 'Moroccan Dirham',
  mdl: 'Moldovan Leu',
  mga: 'Malagasy Ariary',
  mkd: 'Macedonian Denar',
  mmk: 'Myanma Kyat',
  mnt: 'Mongolian Tugrik',
  mop: 'Macanese Pataca',
  mru: 'Mauritanian Ouguiya',
  mur: 'Mauritian Rupee',
  mvr: 'Maldivian Rufiyaa',
  mwk: 'Malawian Kwacha',
  mxn: 'Mexican Peso',
  myr: 'Malaysian Ringgit',
  mzn: 'Mozambican Metical',
  nad: 'Namibian Dollar',
  ngn: 'Nigerian Naira',
  nok: 'Norwegian Krone',
  npr: 'Nepalese Rupee',
  nzd: 'New Zealand Dollar',
  omr: 'Omani Rial',
  pab: 'Panamanian Balboa',
  pen: 'Peruvian Nuevo Sol',
  pgk: 'Papua New Guinean Kina',
  php: 'Philippine Peso',
  pkr: 'Pakistani Rupee',
  pln: 'Polish Zloty',
  pyg: 'Paraguayan Guarani',
  qar: 'Qatari Rial',
  ron: 'Romanian Leu',
  rsd: 'Serbian Dinar',
  rub: 'Russian Ruble',
  rwf: 'Rwandan Franc',
  sar: 'Saudi Riyal',
  scr: 'Seychellois Rupee',
  sdg: 'Sudanese Pound',
  sek: 'Swedish Krona',
  sgd: 'Singapore Dollar',
  shp: 'Saint Helena Pound',
  sll: 'Sierra Leonean Leone',
  sos: 'Somali Shilling',
  srd: 'Surinamese Dollar',
  syp: 'Syrian Pound',
  szl: 'Swazi Lilangeni',
  thb: 'Thai Baht',
  tjs: 'Tajikistani Somoni',
  tmt: 'Turkmenistani Manat',
  tnd: 'Tunisian Dinar',
  try: 'Turkish Lira',
  ttd: 'Trinidad and Tobago Dollar',
  twd: 'New Taiwan Dollar',
  tzs: 'Tanzanian Shilling',
  uah: 'Ukrainian Hryvnia',
  ugx: 'Ugandan Shilling',
  usd: 'United States Dollar',
  uyu: 'Uruguayan Peso',
  uzs: 'Uzbekistan Som',
  vnd: 'Vietnamese Dong',
  vuv: 'Vanuatu Vatu',
  wst: 'Samoan Tala',
  xaf: 'CFA Franc BEAC',
  xcd: 'East Caribbean Dollar',
  xdr: 'Special Drawing Rights',
  xof: 'CFA Franc BCEAO',
  xpf: 'CFP Franc',
  yer: 'Yemeni Rial',
  zar: 'South African Rand',
  zmw: 'Zambian Kwacha',
  zwl: 'Zimbabwean Dollar'
} as const;

export const ALL_CURRENCY_SYMBOLS_LATIN = {
  aed: 'د.إ',
  afn: '؋',
  all: 'L',
  amd: '֏',
  ang: 'ƒ',
  aoa: 'Kz',
  ars: '$',
  aud: '$',
  awg: 'ƒ',
  azn: '₼',
  bam: 'KM',
  bbd: '$',
  bdt: '৳',
  bgn: 'лв',
  bhd: '.د.ب',
  bif: 'Fr',
  bmd: '$',
  bnd: '$',
  bob: 'Bs.',
  brl: 'R$',
  bsd: '$',
  btn: 'Nu.',
  bwp: 'P',
  bzd: '$',
  cad: '$',
  cdf: 'FC',
  chf: 'CHF',
  clp: '$',
  cnh: '¥',
  cny: '¥',
  cop: '$',
  cup: '₱',
  cve: '$',
  czk: 'Kč',
  djf: 'Fdj',
  dkk: 'kr',
  dop: 'RD$',
  dzd: 'د.ج',
  egp: '£',
  ern: 'Nfk',
  etb: 'Br',
  eur: '€',
  fjd: 'FJ$',
  fkp: '£',
  gbp: '£',
  gel: '₾',
  ghs: 'GH₵',
  gip: '£',
  gmd: 'D',
  gnf: 'FG',
  gtq: 'Q',
  gyd: '$',
  hkd: 'HK$',
  hnl: 'L',
  hrk: 'kn',
  htg: 'G',
  huf: 'Ft',
  idr: 'Rp',
  ils: '₪',
  inr: '₹',
  iqd: 'ع.د',
  irr: '﷼',
  isk: 'kr',
  jep: '£',
  jmd: 'J$',
  jod: 'د.ا',
  jpy: '¥',
  kes: 'KSh',
  kgs: 'лв',
  khr: '៛',
  kmf: 'CF',
  kpw: '₩',
  krw: '₩',
  kwd: 'د.ك',
  kyd: '$',
  kzt: '〒',
  lak: '₭',
  lbp: 'ل.ل',
  lkr: '₨',
  lrd: '$',
  lsl: 'L',
  lyd: 'ل.د',
  mad: 'د.م.',
  mdl: 'L',
  mga: 'Ar',
  mkd: 'ден',
  mmk: 'K',
  mnt: '₮',
  mop: 'MOP$',
  mru: 'UM',
  mur: '₨',
  mvr: 'MVR',
  mwk: 'MK',
  mxn: '$',
  myr: 'RM',
  mzn: 'MT',
  nad: '$',
  ngn: '₦',
  nok: 'kr',
  npr: '₨',
  nzd: '$',
  omr: 'ر.ع.',
  pab: 'B/.',
  pen: 'S/',
  pgk: 'K',
  php: '₱',
  pkr: '₨',
  pln: 'zł',
  pyg: '₲',
  qar: 'ر.ق',
  ron: 'lei',
  rsd: 'дин.',
  rub: '₽',
  rwf: 'RF',
  sar: 'ر.س',
  scr: 'SR',
  sdg: 'ج.س.',
  sek: 'kr',
  sgd: 'S$',
  shp: '£',
  sll: 'Le',
  sos: 'Sh',
  srd: '$',
  syp: '£',
  szl: 'L',
  thb: '฿',
  tjs: 'SM',
  tmt: 'T',
  tnd: 'د.ت',
  try: '₺',
  ttd: 'TT$',
  twd: 'NT$',
  tzs: 'TSh',
  uah: '₴',
  ugx: 'USh',
  usd: '$',
  uyu: '$U',
  uzs: 'UZS',
  vnd: '₫',
  vuv: 'VT',
  wst: 'WS$',
  xaf: 'FCFA',
  xcd: 'EC$',
  xdr: 'XDR',
  xof: 'CFA',
  xpf: 'CFP',
  yer: '﷼',
  zar: 'R',
  zmw: 'ZK',
  zwl: 'Z$'
} as const;

export type CurrencySymbols = keyof typeof ALL_CURRENCIES;
export type CurrencyNames = (typeof ALL_CURRENCIES)[CurrencySymbols];
export type CurrencySymbolsLatin = (typeof ALL_CURRENCY_SYMBOLS_LATIN)[CurrencySymbols];

export type CurrencyData = {
  name: CurrencyNames;
  symbol: CurrencySymbols;
  latinSymbol: CurrencySymbolsLatin;
};

export type AllCurrenciesDataType = Array<CurrencyData>;

export const ALL_CURRENCIES_DATA: AllCurrenciesDataType = Object.entries(ALL_CURRENCIES).map(
  ([symbol, name]) => ({
    name: name as CurrencyNames,
    symbol: symbol as CurrencySymbols,
    latinSymbol: ALL_CURRENCY_SYMBOLS_LATIN[symbol as CurrencySymbols]
  })
);
